version: "2"

services:

    minio:
        image: docker.io/bitnami/minio:2021.6.17
        environment: 
        - MINIO_ACCESS_KEY=minio-access-key
        - MINIO_SECRET_KEY=minio-secret-key
        expose:
        - 9000
        ports:
        - 9000:9000
        volumes:
        - ./docker-compose/minio/data:/data
        
    prometheus:
        image: docker.io/bitnami/prometheus:2
        volumes:
        - ./docker-compose/prometheus/conf:/opt/bitnami/prometheus/conf
        # for persisting prometheus data
        #- ./docker-compose/prometheus/data:/opt/bitnami/prometheus/data
        expose:
        - 9090
        ports:
        - 9090:9090

    grafana:
        image: docker.io/bitnami/grafana:7
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=12345
        volumes:
            - ./docker-compose/grafana/conf/provisioning/datasources:/opt/bitnami/grafana/conf/provisioning/datasources
            - ./docker-compose/grafana/conf/provisioning/dashboards:/opt/bitnami/grafana/conf/provisioning/dashboards 
            - ./docker-compose/grafana/dashboards:/opt/bitnami/grafana/dashboards
        ports: 
        - 3000:3000
    
    modelapi:
        image: modelapi
        expose:
        - 8080
        ports:
        - 8080:8080
        command: 
        - uvicorn 
        - app:app 
        - --host=0.0.0.0 
        - --port=8080