name: mlops
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - ipykernel
  - pip
  - dvc-s3
  - prometheus-fastapi-instrumentator
  - fastapi
  - uvicorn
  - transformers
  - pytorch
  - cpuonly
  - doit
  - pandas
  - pip: 
    - openapi-python-client
